# Input data
BAS_prealpha: "data/bas_data/pre_alpha_AISIT_0.1.4.csv"

# Model data
arctic_reanalysis: "data/aor_st.nc"
arctic_reanalysis_oxy: "data/aor_oxy.nc"
arctic_reanalysis_oxy_depth10: "data/aor_oxy_depth10.nc"

# AOO index
aoo_index: "data/aoo_index.csv"